add support for "verbosity" flag, disable spinner by default
szpak/gradle-pitest-plugin pull request #321
Opened 2022-11-17 17:56 UTC by C-Otto

fixes #267

2022-11-17 21:57 UTC, szpak requested changes
Thanks for your PR! It looks good, however, as you probably noticed, the regression tests detected that "verbosity" is not compatible with old PIT versions (<1.7.1). As it was released in September 2021, it should not be a problem. Just bump the minimal supported version to 1.7.1 (in `PitestPluginPitVersionFunctionalSpec` - the second constant will be no longer needed) and mention it in the README.

2022-11-17 21:57 UTC, szpak commented on src/test/groovy/info/solidsoft/gradle/pitest/PitestTaskConfigurationSpec.groovy
> +            task.taskArgumentMap()['features'] == null
Good catch!

2022-11-17 21:57 UTC, szpak commented on src/main/groovy/info/solidsoft/gradle/pitest/PitestPluginExtension.groovy
> +    final Property<String> verbosity
Please add Javadoc mentioning possible values, the value used by default, minimal spported PIT version and the `@since` tag (for GPP 1.9.1).

2022-11-18 07:23 UTC, C-Otto commented
I don't really know how to mention the version requirement in the README, feel free to add suggestions! I think we could/should also deprecate `verbose` in favor of `verbosity`.

2022-11-18 20:10 UTC, szpak approved these changes

2022-11-27 22:53 UTC, merged